// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3KZbVnlRYSmgzRGTDimkUuAxLexI3ET4',
    appId: '1:402056177043:web:718da90b3a38b245f2f466',
    messagingSenderId: '402056177043',
    projectId: 'fooddelivery-36ca1',
    authDomain: 'fooddelivery-36ca1.firebaseapp.com',
    storageBucket: 'fooddelivery-36ca1.firebasestorage.app',
    measurementId: 'G-9B1LR07LJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1UtTM98PMXatyezm_WMNmtZPhYfoPTQs',
    appId: '1:402056177043:android:6a8b5e88d262df3df2f466',
    messagingSenderId: '402056177043',
    projectId: 'fooddelivery-36ca1',
    storageBucket: 'fooddelivery-36ca1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZuYCQWdJNHcsffH8iCtUg2Q92rEy_Tv0',
    appId: '1:402056177043:ios:7eeb1e0acc6ccba3f2f466',
    messagingSenderId: '402056177043',
    projectId: 'fooddelivery-36ca1',
    storageBucket: 'fooddelivery-36ca1.firebasestorage.app',
    iosBundleId: 'com.example.shlihKitchen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZuYCQWdJNHcsffH8iCtUg2Q92rEy_Tv0',
    appId: '1:402056177043:ios:7eeb1e0acc6ccba3f2f466',
    messagingSenderId: '402056177043',
    projectId: 'fooddelivery-36ca1',
    storageBucket: 'fooddelivery-36ca1.firebasestorage.app',
    iosBundleId: 'com.example.shlihKitchen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3KZbVnlRYSmgzRGTDimkUuAxLexI3ET4',
    appId: '1:402056177043:web:40562501ecd7e50df2f466',
    messagingSenderId: '402056177043',
    projectId: 'fooddelivery-36ca1',
    authDomain: 'fooddelivery-36ca1.firebaseapp.com',
    storageBucket: 'fooddelivery-36ca1.firebasestorage.app',
    measurementId: 'G-KFK9DTMFEB',
  );
}
